# Generated by Django 3.0.7 on 2021-04-05 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='squirrel',
            fields=[
                ('latitude', models.DecimalField(decimal_places=10, help_text='Latitude of sighting point', max_digits=20)),
                ('longitude', models.DecimalField(decimal_places=10, help_text='Longitude of sighting point', max_digits=20)),
                ('unique_squirrel_id', models.CharField(help_text='Unique ID number', max_length=30, primary_key=True, serialize=False)),
                ('date', models.DateField(help_text='date', max_length=20)),
            ],
        ),
    ]
